"""initial schema

Revision ID: f1b96bce661e
Revises: 
Create Date: 2026-08-06 23:16:59.250940

"""
from alembic import op
import sqlalchemy as sa


revision = 'f1b96bce661e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name_ar', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=False),
    sa.Column('added_by_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_slug', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('promotion_slug', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manager_alerts_telegram_id'), 'manager_alerts', ['telegram_id'], unique=False)
    op.create_table('pending_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('old_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_updates_slug'), 'pending_updates', ['slug'], unique=False)
    op.create_table('promotion_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('click_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_clicks_slug'), 'promotion_clicks', ['slug'], unique=False)
    op.create_index(op.f('ix_promotion_clicks_telegram_id'), 'promotion_clicks', ['telegram_id'], unique=False)
    op.create_table('promotion_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('status_override', sa.String(length=20), nullable=True),
    sa.Column('source_url_override', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_overrides_slug'), 'promotion_overrides', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('age_confirmed_adult', sa.Boolean(), nullable=True),
    sa.Column('is_minor_flagged', sa.Boolean(), nullable=False),
    sa.Column('has_existing_account', sa.Boolean(), nullable=True),
    sa.Column('used_promo_code_confirmed', sa.Boolean(), nullable=False),
    sa.Column('stage', sa.Enum('NEW', 'EXPLORING', 'SPORTS_INTERESTED', 'CASINO_INTERESTED', 'SEEKING_BONUS', 'NEEDS_EXPLANATION', 'HAS_OBJECTION', 'READY_TO_REGISTER', 'ALREADY_REGISTERED', 'NEEDS_POST_SIGNUP_HELP', 'NEEDS_HUMAN_MANAGER', 'INELIGIBLE', name='playerstage'), nullable=False),
    sa.Column('marketing_opt_out', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('promotion_slug', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_telegram_id'), 'conversation_messages', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_telegram_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_promotion_overrides_slug'), table_name='promotion_overrides')
    op.drop_table('promotion_overrides')
    op.drop_index(op.f('ix_promotion_clicks_telegram_id'), table_name='promotion_clicks')
    op.drop_index(op.f('ix_promotion_clicks_slug'), table_name='promotion_clicks')
    op.drop_table('promotion_clicks')
    op.drop_index(op.f('ix_pending_updates_slug'), table_name='pending_updates')
    op.drop_table('pending_updates')
    op.drop_index(op.f('ix_manager_alerts_telegram_id'), table_name='manager_alerts')
    op.drop_table('manager_alerts')
    op.drop_table('audit_log')
    op.drop_table('admin_countries')
    # ### end Alembic commands ###
